options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "app.yaml"]
    # Deploy ke App Engine menggunakan app.yaml
