options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "alpine"
    entrypoint: "sh"
    args:
      - -c
      - |
        echo "service: bpwindonesia-be" > app.yaml
        echo "runtime: nodejs20" >> app.yaml
        echo "env_variables:" >> app.yaml
        echo "  DB_HOST: '${_DB_HOST}'" >> app.yaml
        echo "  DB_NAME: '${_DB_NAME}'" >> app.yaml
        echo "  DB_USER: '${_DB_USER}'" >> app.yaml
        echo "  DB_PASS: '${_DB_PASS}'" >> app.yaml
        echo "  CLOUD_NAME: '${_CLOUD_NAME}'" >> app.yaml
        echo "  CLOUD_API_KEY: '${_CLOUD_API_KEY}'" >> app.yaml
        echo "  CLOUD_API_SECRET: '${_CLOUD_API_SECRET}'" >> app.yaml
        echo "  JWT_SECRET: '${_JWT_SECRET}'" >> app.yaml
        echo "  JWT_REFRESH_SECRET: '${_JWT_REFRESH_SECRET}'" >> app.yaml
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "app.yaml"]
    # Deploy ke App Engine menggunakan app.yaml
